# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deno CI

on:
  push:
    branches: [ deno ]
  pull_request:
    branches: [ deno ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: [ "v1.0.0", "v0.42.0", "v1.x", "v0.x", "nightly" ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno ${{ matrix.deno }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno run --allow-read --allow-run tests/run.js
